### ISSUE TITLE
Duplicate class a.a found in modules rpointcardsdk-partner-2.4.0.aar -> com.adyen.checkout:twint:5.6.0

### ISSUE THREAD

**Issue by naidu-ba1** [Adyen/adyen-react-native#551]
We started migrating react native adyen in our project to latest version 2.4.1. While doing that we got below error. 

Execution failed for task ':app:checkReleaseDuplicateClasses'. > A failure occurred while executing com.***.build.gradle.internal.tasks.CheckDuplicatesRunnable > Duplicate class a.a found in modules rpointcardsdk-partner-2.4.0.aar -> jetified-rpointcardsdk-partner-2.4.0-runtime (rpointcardsdk-partner-2.4.0.aar) and twint-5.6.0.aar -> jetified-twint-5.6.0-runtime (com.adyen.checkout:twint:5.6.0) Go to the documentation to learn how to <a href="d.***.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>. 

Android builds are impacted with this. 

Solution tried: 

Based on the suggestion given here https://github.com/Adyen/adyen-android/issues/1767#issuecomment-2317414344, we have tried to update com.adyen.checkout:drop-in to 5.7.0 in build.gradle. This fix worked fine for debug builds but threw below error for release builds.

 ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/runner/work/1/s/***/app/build/outputs/mapping/release/missing_rules.txt.ERROR: R8: Missing class com.adyen.checkout.card.CardBrand (referenced from: void com.adyenreactnativesdk.configuration.CardConfigurationParser.applyConfiguration(com.adyen.checkout.card.CardConfiguration$Builder) and 1 other context)Missing class com.adyen.checkout.card.CardType$Companion (referenced from: java.util.List com.adyenreactnativesdk.configuration.CardConfigurationParser.getSupportedCardTypes$adyen_react_native_release())Missing class com.adyen.checkout.card.CardType (referenced from: java.util.List com.adyenreactnativesdk.configuration.CardConfigurationParser.getSupportedCardTypes$adyen_react_native_release())Task :app:minifyReleaseWithR8 FAILED> Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPEDASM Instrumentation process wasn't able to resolve some classes, this means thatthe instrumented classes might contain corrupt stack frames. Make sure thedependencies that contain these classes are on the runtime or the providedclasspath. Otherwise, the jvm might fail to load the corrupt classes at runtimewhen running in a jvm environment like unit tests.Classes that weren't resolved:> com.google.***.gms.maps.model.Dot> com.google.***.gms.maps.model.Dash> com.google.***.gms.maps.model.ButtCap> com.google.***.gms.maps.model.RoundCap> com.google.***.gms.maps.model.SquareCap> com.google.***.gms.maps.model.LatLngBounds> com.google.***.gms.maps.model.BitmapDescriptor> com.mparticle.identity.MParticleUser> com.mparticle.identity.AliasRequest> com.facebook.react.bridge.ReadableMap-- 22 more classes --FAILURE: Build failed with an exception.* What went wrong:Execution failed for task ':app:minifyReleaseWithR8'.> A failure occurred while executing com.***.build.gradle.internal.tasks.R8Task$R8Runnable > Compilation failed to complete

 We have also tried to exclude twint from our project, but that also didn't work.

implementation('com.adyen.checkout:drop-in:5.6.0') {     
     // TODO: remove this when updating to 5.7.0    
     exclude group: 'com.adyen.checkout', module: 'twint' 
}

**Comment by descorp** [comment]
Hey @naidu-ba1 

> We have also tried to exclude twint from our project, but that also didn't work.

Have you done it on [node_modules/@adyen/react-native/android/build.gradle](https://github.com/Adyen/adyen-react-native/blob/develop/android/build.gradle#L105-L107) ?

**Comment by naidu-ba1** [comment]
I have tried this in our app build.gradle.

Now I have tried by adding it in react native adyen node module. This solved the error.

**Comment by descorp** [comment]
> This solved the error.

Thanks for confirming! We will investigate further..

What are the steps to reproduce it?

**Comment by descorp** [comment]
This should be resolved on [latest release](https://github.com/Adyen/adyen-react-native/releases/tag/2.5.0)
