### ISSUE TITLE
Cannot find type 'NativeModuleError' in scope

### ISSUE THREAD

**Issue by gunnartorfis** [Adyen/adyen-react-native#904]
**Describe the bug**
After upgrading to 2.9.0 we're getting this build error:

`Cannot find type 'NativeModuleError' in scope`

**To Reproduce**
1. Upgrade to 2.9.0
2. Build iOS

**Screenshots**
<img width="1270" height="457" alt="Image" src="https://github.com/user-attachments/assets/34b34eda-b1bc-4964-8c37-bff1e1f1c370" />

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 2.9.0

**Smartphone (please complete the following information):**
 - Device: iOS 26.2 simulator

**Comment by descorp** [comment]
Hey @gunnartorfis 

Thanks you for feedback!

Could you try `pod update` ?
[`NativeModuleError`](https://github.com/Adyen/adyen-react-native/blob/2.9.0/ios/Components/NativeModuleError.swift) was moved to a standalone file, but should be within the package

**Comment by descorp** [comment]
@gunnartorfis  I am not able to reproduce this locally on a blank RN 0.83.1 app

**Comment by descorp** [comment]
Hey @gunnartorfis 

Are you still facing the issue?
Any steps we can try to reproduce?

**Comment by gunnartorfis** [comment]
@descorp sorry about the late responses. 
I am unable to reproduce this on the latest release.

**Comment by descorp** [comment]
Thank you for feedback @gunnartorfis 💚

**UPD**

Just realised that wrongly marked this issue as duplicate. 
I wonder what was an issue in the first place 🤔

**Comment by gunnartorfis** [comment]
Yep very interesting. We were working on Expo SDK 54 at the time of opening the PR. We're now on 55 with new architecture enabled and have also bumped to the latest Adyen RN release.

**Comment by descorp** [comment]
I'll try Expo 54. Hopefully I can reproduce it..
